consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: video_chunks
publisher:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: sampled_frames
db:
  host: localhost
  database: big_fiubrother
  username: postgres
  password: password
sampling_rate: 4