consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: video_chunks
publisher:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: sampled_frames
db:
  host: localhost
  database: big_fiubrother
  username: fiubrother
  password: alwayswatching
synchronization:
  host: localhost
  port: 2181
storage:
  host: localhost
  access_key: fiubrother
  secret_key: alwayswatching
  bucket: raw_videos
sampling_rate: 4