consumer:
  host: localhost
  queue: video_chunks
  username: fiubrother
  password: alwayswatching
persitance:
  db:
    host: localhost
    name: video_chunks
    user: postgres
    password: password
sampling:
  rate: 4